name: vantech
description: "A new Flutter project for Final Capstone Project Telecommunication Engineering"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  camera_android_camerax: 0.6.7
  camera: 0.11.0
  carousel_slider_plus: ^7.0.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_markdown: ^0.7.2+1
  flutter_native_splash: ^2.3.8
  flutter_svg: ^2.0.9
  google_generative_ai: ^0.4.3
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  mongo_dart: ^0.10.3
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  firebase_auth: ^5.3.3 # versi terbaru
  google_sign_in: ^6.2.2 # versi terbaru
  firebase_core: ^3.8.0
  cloud_firestore:^5.5.0
  location: ^7.0.1
  firebase_database: ^11.2.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^15.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/png/logo.png"
  min_sdk_android: 23
  ios: false
  adaptive_icon_foreground: "assets/png/logo.png"
  adaptive_icon_background: "#5F8F3C"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/svg/
    - assets/png/
    - assets/png/reading.png
    - assets/png/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
